-- TODO: This is all pretty borked right now. I wanted to have the ability to
-- display ping times to 1.1.1.1 and 8.8.8.8 in my status bar with this, but I
-- never really progressed after trying to get it to display multiple status
-- lines. Right now I still have to figure out the best way to update the
-- display with multiple values from the ping result.
ping = {}

-- This was generated by
-- https://web.archive.org/web/20191216145647/http://xqt2.com/asciiIcons.html
local iconAscii = [[ASCII:
....BC....
....GF....
....JK....
.AH....ED.
..........
.a..ML..b.
..........
..........
.d..jk..c.
..........
.OV....SR.
....ml....
....UT....
....PQ....
]]

pingMenu = hs.menubar.new():setIcon(iconAscii)

function pingResult(object, message, seqnum, error)
    if message == "didFinish" then
        avg = tonumber(string.match(object:summary(), '/(%d+.%d+)/'))

        toString = string.format("G: %.1f ms\nC: %.1f ms", avg, avg)
        pingStyle = (hs.styledtext.new(toString, { baselineOffset = -5, font = {name = '.AppleSystemUIFont', size = 10 }, paragraphStyle = { maximumLineHeight = 10} } ) )
        pingMenu:setTitle(pingStyle)

        _log("Ping result: " .. avg .. "ms")
    end
end

local function fetchPing()
    hs.network.ping.ping("8.8.8.8", 1, 0.01, 1.0, "any", pingResult)
end

function ping.init()
    pingTimer = hs.timer.new(10, fetchPing)
    pingTimer:start()
end

return ping
