---
fail_fast: false
ci:
  autofix_commit_msg: '[pre-commit.ci] auto fixes from pre-commit.com hooks'
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip:
    - git-check
    - shellcheck
    - shfmt
    - check-symlinks
    - fish
    - fish_indent

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: check-symlinks
      - id: forbid-new-submodules
  - repo: https://github.com/Kuniwak/vint
    rev: v0.4a3
    hooks:
      - id: vint
        exclude: tilde/.config/nvim/autoload/plug.vim
  - repo: https://github.com/hugoh/pre-commit-fish.git
    rev: v1.2
    hooks:
      - id: fish_syntax
      - id: fish_indent
  - repo: https://github.com/crate-ci/typos
    rev: v1.3.4
    hooks:
      - id: typos
  - repo: https://github.com/hadolint/hadolint
    rev: v2.8.0
    hooks:
      - id: hadolint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: git-check
      - id: shellcheck
      - id: shfmt
