tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "jmhobbs/parrot"
brew "adns"
brew "gdbm"
brew "libyaml"
brew "openssl"
brew "sqlite"
brew "python"
brew "ansible"
brew "autojump"
brew "automake"
brew "autossh"
brew "bash"
brew "bonnie++"
brew "brew-cask-completion"
brew "cowsay"
brew "coreutils"
brew "cpanminus"
brew "curl"
brew "lame"
brew "xvid"
brew "ffmpeg"
brew "fish"
brew "flake8"
brew "fortune"
brew "fzf"
brew "libxml2"
brew "xz"
brew "python"
brew "gettext"
brew "glances"
brew "git"
brew "git-extras"
brew "git-flow"
brew "git-lfs"
brew "gnupg", link: false
brew "gnutls"
brew "go"
brew "gource"
brew "gpg2"
brew "grc"
brew "gzip"
brew "htop"
brew "hub"
brew "ifstat"
brew "iftop"
brew "irssi"
brew "oniguruma"
brew "jq"
brew "jrnl"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "lastpass-cli"
brew "libdbi"
brew "mas"
brew "mercurial"
brew "mosh"
brew "mysql@5.7", link: true, restart_service:true
brew "mytop"
brew "nload"
brew "nmap"
brew "node"
brew "pandoc"
brew "percona-toolkit"
brew "perl"
brew "pinentry-mac"
brew "pkg-config"
brew "postgresql", restart_service: true
brew "postgis"
brew "pre-commit"
brew "pyenv"
brew "redis", restart_service: true
brew "repo"
brew "ripgrep"
brew "ruby"
brew "rbenv"
brew "s3cmd"
brew "screenfetch"
brew "sipcalc"
brew "sl"
brew "stunnel"
brew "terraform"
brew "textql"
brew "the_silver_searcher"
brew "thefuck"
brew "tig"
brew "tmux"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "yamllint"
brew "z"
brew "zlib"
brew "heroku/brew/heroku"
brew "jmhobbs/parrot/terminal-parrot"
cask "1password"
cask "alfred"
cask "amethyst"
cask "bartender"
cask "dropbox"
cask "daisydisk"
cask "flux"
cask "firefox"
cask "google-chrome"
cask "hazel"
cask "hammerspoon"
cask "java"
cask "keybase"
cask "macupdater"
cask "menumeters"
cask "postman"
cask "prime95"
cask "vlc"
mas "Cinebench", id: 1438772273
mas "Day One", id: 1055511498
mas "GarageBand", id: 682658836
mas "HazeOver", id: 430798174
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Todoist", id: 585829637
mas "ToothFairy", id: 1191449274
mas "Xcode", id: 497799835
