# common ================================================================== {{{
[tasks.common]
    deps = ["submodules"]
    links = [
        [".config/fish"],
        [".config/terminal"],
        [".config/tmux"],
        [".global_gitignore"],
        [".gnupg/gpg-agent.conf"],
        [".gnupg/gpg.conf"],
        [".hammerspoon"],
        [".mytop"],
        [".psqlrc"],
        [".terminfo"],
        [".tmux.conf"],
        [".vim"],
        [".vimrc"],
        [".yamllint"],
    ]
    templates = [
        [".gitconfig"]
    ]

[tasks.submodules]
    cmds = [
        ["git", "submodule", "update", "--init", "--remote"],
    ]

[tasks.keybase]
    cmds = [
        ["@install", "keybase"],
        ["keybase", "login"],
    ]

[tasks.secrets]
    accepts = [["keybase", "login"]]
    cmds = [
        ["git", "clone", "keybase://private/king/dotfiles-secrets", "~/.secrets/"],
        ["chmod", "0700", "~/.secrets"],
    ]

[tasks.pip]
    accepts = [["which", "pip3"]]
    cmds = [
        ["pip3", "install", "vim-vint", "gmail-yaml-filters"],
    ]

[tasks.fish]
    rejects = [
            ["which", "fish"],
            ["echo", "$SHELL", "|", "grep", "fish"],
        ]
    cmds = [["chsh", "-s", "/usr/bin/fish"]]

[tasks.fish_completions]
    accepts = [
            ["which", "fish"],
            ["echo", "$SHELL", "|", "grep", "fish"],
    ]
    envs = [["CHECKOUT", "$HOME/.local/homemaker"]]
    cmds = [
         ["mkdir", "-p", "$CHECKOUT"],
         ["git", "clone", "https://github.com/evanlucas/fish-kubectl-completions", "$CHECKOUT/fkc"],
         ["cp", "-fp", "$CHECKOUT/fkc/completions/kubectl.fish", "$HOME/.config/fish/completions"],
         ["ln", "-s", "/Applications/Docker.app/Contents/Resources/etc/docker.fish-completion", "$HOME/.config/fish/completions/docker.fish"],
         ["rm", "-rf", "$CHECKOUT"],
    ]

[tasks.iterm2]
    rejects = [["functions", "imgcat"]]
    cmds = [
        ["curl", "-L", "//iterm2.com/shell_integration/install_shell_integration_and_utilities.sh", "|", "bash"],
        ["rm -f", "~/.iterm_shell_integration.fish"],
    ]
[tasks.terminfo]
    accepts = ["which", "tic"]
    cmds = [
        ["tic", "-o", "$HOME/terminfo","tmux.terminfo"],
        ["tic", "-o", "$HOME/terminfo","tmux-256color.terminfo"],
        ["tic", "-o", "$HOME/terminfo","xterm-256color.terminfo"],
    ]

# ========================================================================= }}}
# meta ==================================================================== {{{
[tasks.default]
    deps = ["common", "bininstall", "systemconfig", "pip", "fish", "iterm2"]
# ========================================================================= }}}
# macOS =================================================================== {{{
[tasks.installbrew__macos]
    rejects = [["which", "brew"]]
    cmds = [
        ["/usr/bin/ruby", "-e", '"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'],
        ["brew", "update"],
    ]

[tasks.bininstall__macos]
    deps = ["installbrew"]
    cmds = [
        ["brew", "bundle", "install", "--file=$HM_SRC/../Brewfile"],
        ["brew", "cleanup"],
    ]

[tasks.systemconfig__macos]
    cmds = [
        ["./Darwin/defaults.sh"],
    ]

[macros.install__macos]
    deps = ["installbrew"]
    prefix = ["brew", "install"]

# ========================================================================= }}}
