# common ================================================================== {{{
[tasks.links]
    links = [
        [".config/fish"],
        [".config/flake8"],
        [".config/terminal"],
        [".config/tmux"],
        [".global_gitignore"],
        [".gnupg/gpg.conf"],
        [".mytop"],
        [".psqlrc"],
        [".terminfo"],
        [".tmux.conf"],
        [".vim"],
        [".vimrc"],
        [".yamllint"],
    ]
    templates = [
        [".gitconfig"],
        [".gnupg/gpg-agent.conf"],
        [".ssh/config"],
    ]

[tasks.keybase]
    accepts = [["which", "keybase"]]
    cmds = [
        ["keybase", "login"],
    ]

[tasks.secrets]
    deps = ["keybase"]
    cmds = [
        ["git", "clone", "keybase://private/king/dotfiles-secrets", "~/.secrets/"],
        ["chmod", "0700", "~/.secrets"],
    ]

[tasks.pip]
    accepts = [["which", "pip3"]]
    cmds = [
        ["pip3", "install", "vim-vint", "gmail-yaml-filters"],
    ]

[tasks.npm]
accepts = [["which", "npm"]]
    cmds = [
        ["npm", "install", "sign-bunny", "markcat", "bash-language-server", "obs-cli", "do-not-disturb-cli"],
    ]

[tasks.go]
accepts = [["which", "go"]]
    envs = [
            ["GO111MODULE", "on"],
        ]
    cmds = [
        ["go", "get", "golang.org/x/tools/gopls@latest"],
    ]

[tasks.fish]
    rejects = [
            ["which", "fish"],
            ["echo", "$SHELL", "|", "grep", "fish"],
        ]
    cmds = [["chsh", "-s", "/usr/bin/fish"]]


[tasks.terminfo]
    accepts = [["which", "tic"]]
    cmds = [
        ["tic", "$HOME/.terminfo/tmux.terminfo"],
        ["tic", "$HOME/.terminfo/tmux-256color.terminfo"],
        ["tic", "$HOME/.terminfo/xterm-256color.terminfo"],
    ]

# ========================================================================= }}}
# meta ==================================================================== {{{
[tasks.default]
    deps = ["links", "systemconfig", "pip", "npm", "go", "fish", "fish_completions", "terminfo"]

# ========================================================================= }}}
# macOS =================================================================== {{{
[tasks.links__darwin]
    links = [
        [".hammerspoon"],
    ]
[tasks.systemconfig__darwin]
    cmds = [
        ["$HM_SRC/../Darwin/defaults.sh"],
    ]

[tasks.fish_completions__darwin]
envs = [["CHECKOUT", "$HOME/.local/homemaker"]]
    cmds = [
        ["mkdir", "-p", "$CHECKOUT"],
        ["mkdir", "-p", "$HOME/.config/fish/completions/"],
        ["git", "clone", "https://github.com/evanlucas/fish-kubectl-completions", "$CHECKOUT/fkc"],
        ["cp", "-fp", "$CHECKOUT/fkc/completions/kubectl.fish", "$HOME/.config/fish/completions/"],
        ["ln", "-s", "/Applications/Docker.app/Contents/Resources/etc/docker.fish-completion", "$HOME/.config/fish/completions/docker.fish"],
        ["rm", "-rf", "$CHECKOUT"],
    ]

[macros.install__darwin]
    prefix = ["brew", "install"]
# ========================================================================= }}}
# *nix =-================================================================== {{{
[tasks.keybase__nix]
    accepts = [["which", "keybase"]]
        cmds = [
        ["keybase", "login"],
        ["keybase", "config", "set", "gpg.command", "/usr/bin/qubes-gpg-client-wrapper"],
    ]

[tasks.systemconfig__nix]
    cmds = [["true"]]

[tasks.fish_completions__nix]
    cmds = [["true"]]
# ========================================================================= }}}
