# common ================================================================== {{{
[tasks.links]
    links = [
        [".applescript"],
        [".config/bat"],
        [".config/fish"],
        [".config/flake8"],
        [".config/nvim"],
        [".config/terminal"],
        [".config/tmux"],
        [".gitconfig"],
        [".global_gitignore"],
        [".gnupg/gpg-agent.conf"],
        [".gnupg/gpg.conf"],
        [".mytop"],
        [".psqlrc"],
        [".terminfo"],
        [".tmux.conf"],
        [".vintrc"],
        [".yamllint"],
        ["Library/LaunchAgents/com.local.KeyRemapping.plist"],
    ]

[tasks.pip]
    accepts = [["which", "pip3"]]
    cmds = [
        ["pip3", "install", "gmail-yaml-filters", "pynvim"],
    ]

[tasks.npm]
accepts = [["which", "npm"]]
    cmds = [
        ["npm", "install", "markcat", "ipfs-deploy"],
    ]

[tasks.go]
accepts = [["which", "go"]]
    envs = [
            ["GO111MODULE", "on"],
        ]
    cmds = [
        ["go", "install", "golang.org/x/tools/gopls@latest"],
    ]

[tasks.fish]
    rejects = [
            ["which", "fish"],
            ["echo", "$SHELL", "|", "grep", "fish"],
        ]
    cmds = [["chsh", "-s", "/usr/bin/fish"]]

[tasks.vimplug]
    cmds = [
        ["nvim", "-es", "-u", "~/.config/nvim/init.vim", "-i", "NONE", "-c" , "'PlugUpdate'", "-c", "'qa'"],
    ]

[tasks.terminfo]
    accepts = [["which", "tic"]]
    cmds = [
        ["tic", "$HOME/.terminfo/tmux.terminfo"],
        ["tic", "$HOME/.terminfo/tmux-256color.terminfo"],
        ["tic", "$HOME/.terminfo/xterm-256color.terminfo"],
    ]

[tasks.fish_links]
    cmds = [
        ["ln", "-s", "$HOME/.local/share/nvim/plugged/fzf/shell/key-bindings.fish", "$HOME/.config/fish/functions/fzf_key_bindings.fish"],
    ]


# ========================================================================= }}}
# meta ==================================================================== {{{
[tasks.default]
    deps = ["links", "systemconfig", "pip", "npm", "go", "fish", "fish_completions", "fish_links", "terminfo"]

# ========================================================================= }}}
# macOS =================================================================== {{{
[tasks.links__darwin]
    links = [
        [".hammerspoon"],
    ]
[tasks.systemconfig__darwin]
    cmds = [
        ["$HM_SRC/../Darwin/defaults.sh"],
    ]

[tasks.fish_completions__darwin]
envs = [["CHECKOUT", "$HOME/.local/homemaker"]]
    cmds = [
        ["mkdir", "-p", "$CHECKOUT"],
        ["mkdir", "-p", "$HOME/.config/fish/completions/"],
        ["git", "clone", "https://github.com/evanlucas/fish-kubectl-completions", "$CHECKOUT/fkc"],
        ["cp", "-fp", "$CHECKOUT/fkc/completions/kubectl.fish", "$HOME/.config/fish/completions/"],
        ["ln", "-s", "/Applications/Docker.app/Contents/Resources/etc/docker.fish-completion", "$HOME/.config/fish/completions/docker.fish"],
        ["rm", "-rf", "$CHECKOUT"],
    ]

[macros.install__darwin]
    prefix = ["brew", "install"]
# ========================================================================= }}}
# *nix ==================================================================== {{{
[tasks.keybase__nix]
    accepts = [["which", "keybase"]]
        cmds = [
        ["keybase", "login"],
        ["keybase", "config", "set", "gpg.command", "/usr/bin/qubes-gpg-client-wrapper"],
    ]

[tasks.systemconfig__nix]
    cmds = [["true"]]

[tasks.fish_completions__nix]
    cmds = [["true"]]
# ========================================================================= }}}
