# common ================================================================== {{{
[tasks.links]
    links = [
        [".applescript"],
        [".config/bat"],
        [".config/fish"],
        [".config/flake8"],
        [".config/nvim"],
        [".config/terminal"],
        [".config/tmux"],
        [".global_gitignore"],
        [".gnupg/gpg.conf"],
        [".mytop"],
        [".psqlrc"],
        [".terminfo"],
        [".tmux.conf"],
        [".vintrc"],
        [".yamllint"],
    ]
    templates = [
        [".gitconfig"],
        [".gnupg/gpg-agent.conf"],
    ]

[tasks.pip]
    accepts = [["which", "pip3"]]
    cmds = [
        ["pip3", "install", "vim-vint", "gmail-yaml-filters", "pynvim"],
    ]

[tasks.npm]
accepts = [["which", "npm"]]
    cmds = [
        ["npm", "install", "markcat", "bash-language-server", "ipfs-deploy", "vim-language-server", ],
    ]

[tasks.go]
accepts = [["which", "go"]]
    envs = [
            ["GO111MODULE", "on"],
        ]
    cmds = [
        ["go", "install", "golang.org/x/tools/gopls@latest"],
    ]

[tasks.fish]
    rejects = [
            ["which", "fish"],
            ["echo", "$SHELL", "|", "grep", "fish"],
        ]
    cmds = [["chsh", "-s", "/usr/bin/fish"]]


[tasks.nvim2vim]
    cmds = [
        ["mkdir", "-p", "$HOME/.vim"],
        ["ln", "-s", "$HOME/.config/nvim/init.vim", "$HOME/.vimrc"],
        ["ln", "-s", "$HOME/.config/nvim/autoload", "$HOME/.vim/autoload"],
        ["ln", "-s", "$HOME/.config/nvim/ftdetect", "$HOME/.vim/ftdetect"],
        ["ln", "-s", "$HOME/.config/nvim/ftplugin", "$HOME/.vim/ftplugin"],
        ["ln", "-s", "$HOME/.config/nvim/plug.vim", "$HOME/.vim/plug.vim"],
        ["ln", "-s", "$HOME/.config/nvim/plugin",   "$HOME/.vim/plugin"],
        ["ln", "-s", "$HOME/.config/nvim/spell",    "$HOME/.vim/spell"],
    ]

[tasks.vimplug]
    cmds = [
        ["vim", "-es", "-u", "~/.vimrc", "-i", "NONE", "-c" , "'PlugInstall'", "-c", "'qa'"],
        ["nvim", "-es", "-u", "~/.config/nvim/init.vim", "-i", "NONE", "-c" , "'PlugInstall'", "-c", "'qa'"],
    ]

[tasks.terminfo]
    accepts = [["which", "tic"]]
    cmds = [
        ["tic", "$HOME/.terminfo/tmux.terminfo"],
        ["tic", "$HOME/.terminfo/tmux-256color.terminfo"],
        ["tic", "$HOME/.terminfo/xterm-256color.terminfo"],
    ]

# ========================================================================= }}}
# meta ==================================================================== {{{
[tasks.default]
    deps = ["links", "systemconfig", "pip", "npm", "go", "fish", "fish_completions", "terminfo", "nvim2vim"]

# ========================================================================= }}}
# macOS =================================================================== {{{
[tasks.links__darwin]
    links = [
        [".hammerspoon"],
    ]
[tasks.systemconfig__darwin]
    cmds = [
        ["$HM_SRC/../Darwin/defaults.sh"],
    ]

[tasks.fish_completions__darwin]
envs = [["CHECKOUT", "$HOME/.local/homemaker"]]
    cmds = [
        ["mkdir", "-p", "$CHECKOUT"],
        ["mkdir", "-p", "$HOME/.config/fish/completions/"],
        ["git", "clone", "https://github.com/evanlucas/fish-kubectl-completions", "$CHECKOUT/fkc"],
        ["cp", "-fp", "$CHECKOUT/fkc/completions/kubectl.fish", "$HOME/.config/fish/completions/"],
        ["ln", "-s", "/Applications/Docker.app/Contents/Resources/etc/docker.fish-completion", "$HOME/.config/fish/completions/docker.fish"],
        ["rm", "-rf", "$CHECKOUT"],
    ]

[macros.install__darwin]
    prefix = ["brew", "install"]
# ========================================================================= }}}
# *nix =-================================================================== {{{
[tasks.keybase__nix]
    accepts = [["which", "keybase"]]
        cmds = [
        ["keybase", "login"],
        ["keybase", "config", "set", "gpg.command", "/usr/bin/qubes-gpg-client-wrapper"],
    ]

[tasks.systemconfig__nix]
    cmds = [["true"]]

[tasks.fish_completions__nix]
    cmds = [["true"]]
# ========================================================================= }}}
