---
policies:
  # Disable this since a lot of my .vim configuration files contain UTF-8 characters
  ProhibitMissingScriptEncoding:
    enabled: false

  # I'm also going to set nocompatible because modern vim/nvim
  ProhibitSetNoCompatible:
    enabled: false

  # I have become a neovim convert.
  env:
    neovim: true

