---
name: Cancel
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: docker-image.yml, snyk-container-analysis.yml
          access_token: ${{ github.token }}
