---
name: Docker Image Build

on:
  - pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@163217dfcd28294438ea1c1c149cfaf66eec283e
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
