name:  Secuirty
on: [push]

jobs:
  Secrets:
    runs-on: [ubuntu-latest]
    steps:
    - name: Secret Scan
      uses: max/secret-scan@1.0.0
  GitLeaks:
    runs-on: [ubuntu-latest]
    steps:
    - name: gitleaks-action
      uses: eshork/gitleaks-action@v1.0.0
